# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8961d365d950695394bda245b3c46713456b71cdce032344815153caad58bf01cc6a92d2b87086530579bee5153326177a5e62d930e95a68ab5d3125ab54051a

test:
  secret_key_base: e9cfef06ec7cfdb929976f48e3ada3d4bbd4403e6d16777d5de5b09e56ffac8499fa9a1d4a74c7af5cd536c0bb1962e890d464ab0a095f4fcda3f2932eb314d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
